[package]
name = "genhub-co"
version = "0.1.0"
authors = ["GenHub team <team@genhub.co>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
yew-router = "0.14.0"